apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sboot
  janus-idp.io/tekton: sboot
  backstage.io/kubernetes-id: sboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
