apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: sboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sboot 
  name: sboot
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sboot
    weight: 100 
